document.write('<div align="center"><center>');
document.write('');
document.write('<table border="0" cellpadding="0" cellspacing="0" width="620" bgcolor="#E3DEC8">');
document.write('  <tr>');
document.write('    <td width="42" valign="top" bgcolor="#000000" height="1" colspan="5"><img src="pix.gif"');
document.write('    width="1" height="1"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td width="1" valign="top" bgcolor="#000000" rowspan="11"><img src="pix.gif" width="1"');
document.write('    height="1"></td>');
document.write('    <td width="20" valign="top" bgcolor="#FFFFFF"><img src="pix.gif" width="1" height="1"></td>');
document.write('    <td valign="top" bgcolor="#FFFFFF"><img src="http://38clan.38net.ru/img/irk.gif" width="17" height="64"><img');
document.write('    src="http://38clan.38net.ru/img/logotype.gif" width="251" height="64"><img src="http://38clan.38net.ru/img/spacer.gif"');
document.write('    ><img src="http://38clan.38net.ru/title/guestbook.gif"></td>');
document.write('    <td width="20" valign="top" bgcolor="#FFFFFF"><img src="pix.gif" width="1" height="1"></td>');
document.write('    <td width="1" valign="top" bgcolor="#000000" rowspan="11"><img src="pix.gif" width="1"');
document.write('    height="1"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td width="40" valign="top" bgcolor="#000000" height="1" colspan="3"><img src="pix.gif"');
document.write('    width="1" height="1"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td width="20" valign="top"><img src="pix.gif" width="1" height="1"></td>');
document.write('    <td valign="top"><p align="center"><span class="menufont"><a href="http://38clan.38net.ru/index.html"');
document.write('    class="menufont">Новости</a> <a href="http://38clan.38net.ru/members.html" class="menufont">Члены</a>');
document.write('    <a href="http://38clan.38net.ru/history.html" class="menufont">История</a> <a href="http://38clan.38net.ru/wars.html"');
document.write('    class="menufont">Войны</a> <a href="http://38clan.38net.ru/champs.html" class="menufont">Чемпы</a> <a');
document.write('    href="http://38clan.38net.ru/demos.html" class="menufont">Демки</a> <a href="http://38clan.38net.ru/files.html" class="menufont">Файлы</a>');
document.write('    <a href="http://38clan.38net.ru/photos.html" class="menufont">Фотки</a> <a href="http://38clan.38net.ru/links.html"');
document.write('    class="menufont">Ссылки</a> <a href="http://38clan.38net.ru/articles.html" class="menufont">Статьи</a>');
document.write('    <a href="http://38clan.38net.ru/board.html" class="menufont">Борда</a> <a');
document.write('    href="http://www.guestbook.ru/book.cgi?action=show&user=38clan" class="menufont"');
document.write('    >Книга</a></span></td>');
document.write('    <td width="20" valign="top"><img src="pix.gif" width="1" height="1"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td width="40" valign="top" bgcolor="#000000" height="1" colspan="3"><img src="pix.gif"');
document.write('    width="1" height="1"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('  </tr></table>');